// ======================================================================
// \title  FileStatusEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FileStatus enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Os/Models/FileStatusEnumAc.hpp"

namespace Os {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  FileStatus& FileStatus ::
    operator=(const FileStatus& obj)
  {
    this->e = obj.e;
    return *this;
  }

  FileStatus& FileStatus ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const FileStatus& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool FileStatus ::
    isValid() const
  {
    return ((e >= OP_OK) && (e <= OTHER_ERROR));
  }

  Fw::SerializeStatus FileStatus ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus FileStatus ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void FileStatus ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case OP_OK:
        s = "OP_OK";
        break;
      case DOESNT_EXIST:
        s = "DOESNT_EXIST";
        break;
      case NO_SPACE:
        s = "NO_SPACE";
        break;
      case NO_PERMISSION:
        s = "NO_PERMISSION";
        break;
      case BAD_SIZE:
        s = "BAD_SIZE";
        break;
      case NOT_OPENED:
        s = "NOT_OPENED";
        break;
      case FILE_EXISTS:
        s = "FILE_EXISTS";
        break;
      case NOT_SUPPORTED:
        s = "NOT_SUPPORTED";
        break;
      case INVALID_MODE:
        s = "INVALID_MODE";
        break;
      case INVALID_ARGUMENT:
        s = "INVALID_ARGUMENT";
        break;
      case OTHER_ERROR:
        s = "OTHER_ERROR";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void FileStatus ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
