// ======================================================================
// \title  FileModeEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for FileMode enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Os/Models/FileModeEnumAc.hpp"

namespace Os {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  FileMode& FileMode ::
    operator=(const FileMode& obj)
  {
    this->e = obj.e;
    return *this;
  }

  FileMode& FileMode ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const FileMode& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool FileMode ::
    isValid() const
  {
    return ((e >= OPEN_NO_MODE) && (e <= OPEN_APPEND));
  }

  Fw::SerializeStatus FileMode ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus FileMode ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void FileMode ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case OPEN_NO_MODE:
        s = "OPEN_NO_MODE";
        break;
      case OPEN_READ:
        s = "OPEN_READ";
        break;
      case OPEN_CREATE:
        s = "OPEN_CREATE";
        break;
      case OPEN_WRITE:
        s = "OPEN_WRITE";
        break;
      case OPEN_SYNC_WRITE:
        s = "OPEN_SYNC_WRITE";
        break;
      case OPEN_APPEND:
        s = "OPEN_APPEND";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void FileMode ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
