// ======================================================================
// \title  GenericStatusEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for GenericStatus enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Os/Models/GenericStatusEnumAc.hpp"

namespace Os {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  GenericStatus& GenericStatus ::
    operator=(const GenericStatus& obj)
  {
    this->e = obj.e;
    return *this;
  }

  GenericStatus& GenericStatus ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const GenericStatus& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool GenericStatus ::
    isValid() const
  {
    return ((e >= OP_OK) && (e <= ERROR));
  }

  Fw::SerializeStatus GenericStatus ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus GenericStatus ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void GenericStatus ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case OP_OK:
        s = "OP_OK";
        break;
      case ERROR:
        s = "ERROR";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void GenericStatus ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
