// ======================================================================
// \title  MutexStatusEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for MutexStatus enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Os/Models/MutexStatusEnumAc.hpp"

namespace Os {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  MutexStatus& MutexStatus ::
    operator=(const MutexStatus& obj)
  {
    this->e = obj.e;
    return *this;
  }

  MutexStatus& MutexStatus ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const MutexStatus& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool MutexStatus ::
    isValid() const
  {
    return ((e >= OP_OK) && (e <= ERROR_OTHER));
  }

  Fw::SerializeStatus MutexStatus ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus MutexStatus ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void MutexStatus ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case OP_OK:
        s = "OP_OK";
        break;
      case ERROR_BUSY:
        s = "ERROR_BUSY";
        break;
      case ERROR_DEADLOCK:
        s = "ERROR_DEADLOCK";
        break;
      case ERROR_OTHER:
        s = "ERROR_OTHER";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void MutexStatus ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
