// ======================================================================
// \title  QueueBlockingTypeEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for QueueBlockingType enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Os/Models/QueueBlockingTypeEnumAc.hpp"

namespace Os {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  QueueBlockingType& QueueBlockingType ::
    operator=(const QueueBlockingType& obj)
  {
    this->e = obj.e;
    return *this;
  }

  QueueBlockingType& QueueBlockingType ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const QueueBlockingType& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool QueueBlockingType ::
    isValid() const
  {
    return ((e >= BLOCKING) && (e <= NONBLOCKING));
  }

  Fw::SerializeStatus QueueBlockingType ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus QueueBlockingType ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void QueueBlockingType ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case BLOCKING:
        s = "BLOCKING";
        break;
      case NONBLOCKING:
        s = "NONBLOCKING";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void QueueBlockingType ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
