// ======================================================================
// \title  SeqDispatcher_CmdSequencerStateEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for SeqDispatcher_CmdSequencerState enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Svc/SeqDispatcher/SeqDispatcher_CmdSequencerStateEnumAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  SeqDispatcher_CmdSequencerState& SeqDispatcher_CmdSequencerState ::
    operator=(const SeqDispatcher_CmdSequencerState& obj)
  {
    this->e = obj.e;
    return *this;
  }

  SeqDispatcher_CmdSequencerState& SeqDispatcher_CmdSequencerState ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const SeqDispatcher_CmdSequencerState& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool SeqDispatcher_CmdSequencerState ::
    isValid() const
  {
    return ((e >= AVAILABLE) && (e <= RUNNING_SEQUENCE_NO_BLOCK));
  }

  Fw::SerializeStatus SeqDispatcher_CmdSequencerState ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus SeqDispatcher_CmdSequencerState ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void SeqDispatcher_CmdSequencerState ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case AVAILABLE:
        s = "AVAILABLE";
        break;
      case RUNNING_SEQUENCE_BLOCK:
        s = "RUNNING_SEQUENCE_BLOCK";
        break;
      case RUNNING_SEQUENCE_NO_BLOCK:
        s = "RUNNING_SEQUENCE_NO_BLOCK";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void SeqDispatcher_CmdSequencerState ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
