// ======================================================================
// \title  DpStateEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DpState enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Fw/Dp/DpStateEnumAc.hpp"

namespace Fw {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  DpState& DpState ::
    operator=(const DpState& obj)
  {
    this->e = obj.e;
    return *this;
  }

  DpState& DpState ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const DpState& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool DpState ::
    isValid() const
  {
    return ((e >= UNTRANSMITTED) && (e <= TRANSMITTED));
  }

  Fw::SerializeStatus DpState ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus DpState ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void DpState ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case UNTRANSMITTED:
        s = "UNTRANSMITTED";
        break;
      case PARTIAL:
        s = "PARTIAL";
        break;
      case TRANSMITTED:
        s = "TRANSMITTED";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIu8 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void DpState ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIu8 "", e);
  }

#endif

}
