// ======================================================================
// \title  PolyDbEntryEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for PolyDbEntry enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "config/PolyDbEntryEnumAc.hpp"

namespace Svc {

  namespace PolyDbCfg {

    // ----------------------------------------------------------------------
    // Operators
    // ----------------------------------------------------------------------

    PolyDbEntry& PolyDbEntry ::
      operator=(const PolyDbEntry& obj)
    {
      this->e = obj.e;
      return *this;
    }

    PolyDbEntry& PolyDbEntry ::
      operator=(T e1)
    {
      this->e = e1;
      return *this;
    }

#ifdef BUILD_UT

    std::ostream& operator<<(std::ostream& os, const PolyDbEntry& obj) {
      Fw::String s;
      obj.toString(s);
      os << s;
      return os;
    }

#endif

    // ----------------------------------------------------------------------
    // Member functions
    // ----------------------------------------------------------------------

    bool PolyDbEntry ::
      isValid() const
    {
      return ((e >= POLYDB_ENTRY_00) && (e <= POLYDB_ENTRY_09));
    }

    Fw::SerializeStatus PolyDbEntry ::
      serialize(Fw::SerializeBufferBase& buffer) const
    {
      const Fw::SerializeStatus status = buffer.serialize(
          static_cast<SerialType>(this->e)
      );
      return status;
    }

    Fw::SerializeStatus PolyDbEntry ::
      deserialize(Fw::SerializeBufferBase& buffer)
    {
      SerialType es;
      Fw::SerializeStatus status = buffer.deserialize(es);
      if (status == Fw::FW_SERIALIZE_OK) {
        this->e = static_cast<T>(es);
        if (!this->isValid()) {
          status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
        }
      }
      return status;
    }

#if FW_SERIALIZABLE_TO_STRING

    void PolyDbEntry ::
      toString(Fw::StringBase& sb) const
    {
      Fw::String s;
      switch (e) {
        case POLYDB_ENTRY_00:
          s = "POLYDB_ENTRY_00";
          break;
        case POLYDB_ENTRY_01:
          s = "POLYDB_ENTRY_01";
          break;
        case POLYDB_ENTRY_03:
          s = "POLYDB_ENTRY_03";
          break;
        case POLYDB_ENTRY_04:
          s = "POLYDB_ENTRY_04";
          break;
        case POLYDB_ENTRY_05:
          s = "POLYDB_ENTRY_05";
          break;
        case POLYDB_ENTRY_06:
          s = "POLYDB_ENTRY_06";
          break;
        case POLYDB_ENTRY_07:
          s = "POLYDB_ENTRY_07";
          break;
        case POLYDB_ENTRY_08:
          s = "POLYDB_ENTRY_08";
          break;
        case POLYDB_ENTRY_09:
          s = "POLYDB_ENTRY_09";
          break;
        default:
          s = "[invalid]";
          break;
      }
      sb.format("%s (%" PRIu32 ")", s.toChar(), e);
    }

#elif FW_ENABLE_TEXT_LOGGING

    void PolyDbEntry ::
      toString(Fw::StringBase& sb) const
    {
      sb.format("%" PRIu32 "", e);
    }

#endif

  }

}
