// ======================================================================
// \title  ICARUSTopologyAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for ICARUS topology
// ======================================================================

#include "ICARUS/Top/ICARUSTopologyAc.hpp"

// ----------------------------------------------------------------------
// Component instances
// ----------------------------------------------------------------------

namespace ICARUS {

  ADCS adcs(FW_OPTIONAL_NAME("adcs"));

}

namespace ICARUS {

  Svc::CommandDispatcher cmdDisp(FW_OPTIONAL_NAME("cmdDisp"));

}

namespace ICARUS {

  Drv::TcpClient comDriver(FW_OPTIONAL_NAME("comDriver"));

}

namespace ICARUS {

  Comms comms(FW_OPTIONAL_NAME("comms"));

}

namespace ICARUS {

  Svc::ActiveLogger eventLogger(FW_OPTIONAL_NAME("eventLogger"));

}

namespace ICARUS {

  NandFlash flash(FW_OPTIONAL_NAME("flash"));

}

namespace ICARUS {

  Microcontroller mcu(FW_OPTIONAL_NAME("mcu"));

}

namespace ICARUS {

  Svc::PassiveTextLogger textLogger(FW_OPTIONAL_NAME("textLogger"));

}

namespace ICARUS {

  Svc::PosixTime timeComp(FW_OPTIONAL_NAME("timeComp"));

}

namespace ICARUS {

  Svc::TlmChan tlmSend(FW_OPTIONAL_NAME("tlmSend"));

}

namespace ICARUS {


  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  void initComponents(const TopologyState& state) {
    ICARUS::adcs.init(QueueSizes::ICARUS_adcs, InstanceIds::ICARUS_adcs);
    ICARUS::cmdDisp.init(QueueSizes::ICARUS_cmdDisp, InstanceIds::ICARUS_cmdDisp);
    ICARUS::comDriver.init(InstanceIds::ICARUS_comDriver);
    ICARUS::comms.init(QueueSizes::ICARUS_comms, InstanceIds::ICARUS_comms);
    ICARUS::eventLogger.init(QueueSizes::ICARUS_eventLogger, InstanceIds::ICARUS_eventLogger);
    ICARUS::flash.init(QueueSizes::ICARUS_flash, InstanceIds::ICARUS_flash);
    ICARUS::mcu.init(QueueSizes::ICARUS_mcu, InstanceIds::ICARUS_mcu);
    ICARUS::textLogger.init(InstanceIds::ICARUS_textLogger);
    ICARUS::timeComp.init(InstanceIds::ICARUS_timeComp);
    ICARUS::tlmSend.init(QueueSizes::ICARUS_tlmSend, InstanceIds::ICARUS_tlmSend);
  }

  void configComponents(const TopologyState& state) {
    // Nothing to do
  }

  void setBaseIds() {
    ICARUS::comms.setIdBase(BaseIds::ICARUS_comms);
    ICARUS::mcu.setIdBase(BaseIds::ICARUS_mcu);
    ICARUS::flash.setIdBase(BaseIds::ICARUS_flash);
    ICARUS::adcs.setIdBase(BaseIds::ICARUS_adcs);
    ICARUS::cmdDisp.setIdBase(BaseIds::ICARUS_cmdDisp);
    ICARUS::eventLogger.setIdBase(BaseIds::ICARUS_eventLogger);
    ICARUS::timeComp.setIdBase(BaseIds::ICARUS_timeComp);
    ICARUS::tlmSend.setIdBase(BaseIds::ICARUS_tlmSend);
    ICARUS::textLogger.setIdBase(BaseIds::ICARUS_textLogger);
    ICARUS::comDriver.setIdBase(BaseIds::ICARUS_comDriver);
  }

  void connectComponents() {

    // AltitudeCommandFlow
    ICARUS::comms.set_CommsCmdOut_OutputPort(
        0,
        ICARUS::mcu.get_MicrocontrollerIn_InputPort(0)
    );
    ICARUS::flash.set_FlashCmdOut_OutputPort(
        0,
        ICARUS::adcs.get_ADCSCmdIn_InputPort(0)
    );
    ICARUS::mcu.set_MicrocontrollerOut_OutputPort(
        0,
        ICARUS::flash.get_FlashCmdIn_InputPort(0)
    );

    // Command
    ICARUS::cmdDisp.set_compCmdSend_OutputPort(
        0,
        ICARUS::cmdDisp.get_CmdDisp_InputPort(0)
    );
    ICARUS::cmdDisp.set_compCmdSend_OutputPort(
        2,
        ICARUS::eventLogger.get_CmdDisp_InputPort(0)
    );

    // CommandRegistration
    ICARUS::cmdDisp.set_CmdReg_OutputPort(
        0,
        ICARUS::cmdDisp.get_compCmdReg_InputPort(0)
    );
    ICARUS::eventLogger.set_CmdReg_OutputPort(
        0,
        ICARUS::cmdDisp.get_compCmdReg_InputPort(2)
    );

    // CommandResponse
    ICARUS::cmdDisp.set_CmdStatus_OutputPort(
        0,
        ICARUS::cmdDisp.get_compCmdStat_InputPort(0)
    );
    ICARUS::eventLogger.set_CmdStatus_OutputPort(
        0,
        ICARUS::cmdDisp.get_compCmdStat_InputPort(0)
    );

    // CommsStandardPorts
    ICARUS::cmdDisp.set_compCmdSend_OutputPort(
        1,
        ICARUS::comms.get_cmdIn_InputPort(0)
    );
    ICARUS::comms.set_cmdRegOut_OutputPort(
        0,
        ICARUS::cmdDisp.get_compCmdReg_InputPort(1)
    );
    ICARUS::comms.set_cmdResponseOut_OutputPort(
        0,
        ICARUS::cmdDisp.get_compCmdStat_InputPort(0)
    );
    ICARUS::comms.set_logOut_OutputPort(
        0,
        ICARUS::eventLogger.get_LogRecv_InputPort(0)
    );
    ICARUS::comms.set_logTextOut_OutputPort(
        0,
        ICARUS::textLogger.get_TextLogger_InputPort(0)
    );
    ICARUS::comms.set_timeCaller_OutputPort(
        0,
        ICARUS::timeComp.get_timeGetPort_InputPort(0)
    );

    // Events
    ICARUS::adcs.set_logOut_OutputPort(
        0,
        ICARUS::eventLogger.get_LogRecv_InputPort(0)
    );
    ICARUS::cmdDisp.set_Log_OutputPort(
        0,
        ICARUS::eventLogger.get_LogRecv_InputPort(0)
    );
    ICARUS::eventLogger.set_Log_OutputPort(
        0,
        ICARUS::eventLogger.get_LogRecv_InputPort(0)
    );
    ICARUS::flash.set_logOut_OutputPort(
        0,
        ICARUS::eventLogger.get_LogRecv_InputPort(0)
    );
    ICARUS::mcu.set_logOut_OutputPort(
        0,
        ICARUS::eventLogger.get_LogRecv_InputPort(0)
    );

    // Telemetry
    ICARUS::adcs.set_tlmOut_OutputPort(
        0,
        ICARUS::tlmSend.get_TlmRecv_InputPort(0)
    );
    ICARUS::cmdDisp.set_Tlm_OutputPort(
        0,
        ICARUS::tlmSend.get_TlmRecv_InputPort(0)
    );
    ICARUS::flash.set_tlmOut_OutputPort(
        0,
        ICARUS::tlmSend.get_TlmRecv_InputPort(0)
    );

    // TextEvents
    ICARUS::adcs.set_logTextOut_OutputPort(
        0,
        ICARUS::textLogger.get_TextLogger_InputPort(0)
    );
    ICARUS::cmdDisp.set_LogText_OutputPort(
        0,
        ICARUS::textLogger.get_TextLogger_InputPort(0)
    );
    ICARUS::eventLogger.set_LogText_OutputPort(
        0,
        ICARUS::textLogger.get_TextLogger_InputPort(0)
    );
    ICARUS::flash.set_logTextOut_OutputPort(
        0,
        ICARUS::textLogger.get_TextLogger_InputPort(0)
    );
    ICARUS::mcu.set_logTextOut_OutputPort(
        0,
        ICARUS::textLogger.get_TextLogger_InputPort(0)
    );

    // Time
    ICARUS::adcs.set_timeCaller_OutputPort(
        0,
        ICARUS::timeComp.get_timeGetPort_InputPort(0)
    );
    ICARUS::cmdDisp.set_Time_OutputPort(
        0,
        ICARUS::timeComp.get_timeGetPort_InputPort(0)
    );
    ICARUS::eventLogger.set_Time_OutputPort(
        0,
        ICARUS::timeComp.get_timeGetPort_InputPort(0)
    );
    ICARUS::flash.set_timeCaller_OutputPort(
        0,
        ICARUS::timeComp.get_timeGetPort_InputPort(0)
    );
    ICARUS::mcu.set_timeCaller_OutputPort(
        0,
        ICARUS::timeComp.get_timeGetPort_InputPort(0)
    );
  }

  void regCommands() {
    ICARUS::cmdDisp.regCommands();
    ICARUS::comms.regCommands();
    ICARUS::eventLogger.regCommands();
  }

  void readParameters() {
    // Nothing to do
  }

  void loadParameters() {
    // Nothing to do
  }

  void startTasks(const TopologyState& state) {
    ICARUS::adcs.start(
      static_cast<Os::Task::ParamType>(Priorities::ICARUS_adcs),
      static_cast<Os::Task::ParamType>(StackSizes::ICARUS_adcs),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ICARUS_adcs)
    );
    ICARUS::cmdDisp.start(
      Os::Task::TASK_DEFAULT, // Default priority
      Os::Task::TASK_DEFAULT, // Default stack size
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ICARUS_cmdDisp)
    );
    ICARUS::comms.start(
      static_cast<Os::Task::ParamType>(Priorities::ICARUS_comms),
      static_cast<Os::Task::ParamType>(StackSizes::ICARUS_comms),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ICARUS_comms)
    );
    ICARUS::eventLogger.start(
      Os::Task::TASK_DEFAULT, // Default priority
      Os::Task::TASK_DEFAULT, // Default stack size
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ICARUS_eventLogger)
    );
    ICARUS::flash.start(
      static_cast<Os::Task::ParamType>(Priorities::ICARUS_flash),
      static_cast<Os::Task::ParamType>(StackSizes::ICARUS_flash),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ICARUS_flash)
    );
    ICARUS::mcu.start(
      static_cast<Os::Task::ParamType>(Priorities::ICARUS_mcu),
      static_cast<Os::Task::ParamType>(StackSizes::ICARUS_mcu),
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ICARUS_mcu)
    );
    ICARUS::tlmSend.start(
      Os::Task::TASK_DEFAULT, // Default priority
      Os::Task::TASK_DEFAULT, // Default stack size
      Os::Task::TASK_DEFAULT, // Default CPU
      static_cast<Os::Task::ParamType>(TaskIds::ICARUS_tlmSend)
    );
  }

  void stopTasks(const TopologyState& state) {
    ICARUS::adcs.exit();
    ICARUS::cmdDisp.exit();
    ICARUS::comms.exit();
    ICARUS::eventLogger.exit();
    ICARUS::flash.exit();
    ICARUS::mcu.exit();
    ICARUS::tlmSend.exit();
  }

  void freeThreads(const TopologyState& state) {
    (void) ICARUS::adcs.ActiveComponentBase::join();
    (void) ICARUS::cmdDisp.ActiveComponentBase::join();
    (void) ICARUS::comms.ActiveComponentBase::join();
    (void) ICARUS::eventLogger.ActiveComponentBase::join();
    (void) ICARUS::flash.ActiveComponentBase::join();
    (void) ICARUS::mcu.ActiveComponentBase::join();
    (void) ICARUS::tlmSend.ActiveComponentBase::join();
  }

  void tearDownComponents(const TopologyState& state) {
    // Nothing to do
  }

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  void setup(const TopologyState& state) {
    initComponents(state);
    configComponents(state);
    setBaseIds();
    connectComponents();
    regCommands();
    readParameters();
    loadParameters();
    startTasks(state);
  }

  void teardown(const TopologyState& state) {
    stopTasks(state);
    freeThreads(state);
    tearDownComponents(state);
  }

}
