// ======================================================================
// \title  ICARUSTopologyAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for ICARUS topology
// ======================================================================

#ifndef ICARUS_ICARUSTopologyAc_HPP
#define ICARUS_ICARUSTopologyAc_HPP

#include "Drv/TcpClient/TcpClient.hpp"
#include "ICARUS/Components/ADCS/ADCS.hpp"
#include "ICARUS/Components/Comms/Comms.hpp"
#include "ICARUS/Components/Microcontroller/Microcontroller.hpp"
#include "ICARUS/Components/NandFlash/NandFlash.hpp"
#include "ICARUS/Top/ICARUSTopologyDefs.hpp"
#include "Svc/ActiveLogger/ActiveLogger.hpp"
#include "Svc/CmdDispatcher/CommandDispatcher.hpp"
#include "Svc/PassiveConsoleTextLogger/PassiveTextLogger.hpp"
#include "Svc/PosixTime/PosixTime.hpp"
#include "Svc/TlmChan/TlmChan.hpp"

// ----------------------------------------------------------------------
// Component instances
// ----------------------------------------------------------------------

namespace ICARUS {

  //! adcs
  extern ADCS adcs;

}

namespace ICARUS {

  //! cmdDisp
  extern Svc::CommandDispatcher cmdDisp;

}

namespace ICARUS {

  //! comDriver
  extern Drv::TcpClient comDriver;

}

namespace ICARUS {

  //! comms
  extern Comms comms;

}

namespace ICARUS {

  //! eventLogger
  extern Svc::ActiveLogger eventLogger;

}

namespace ICARUS {

  //! flash
  extern NandFlash flash;

}

namespace ICARUS {

  //! mcu
  extern Microcontroller mcu;

}

namespace ICARUS {

  //! textLogger
  extern Svc::PassiveTextLogger textLogger;

}

namespace ICARUS {

  //! timeComp
  extern Svc::PosixTime timeComp;

}

namespace ICARUS {

  //! tlmSend
  extern Svc::TlmChan tlmSend;

}

namespace ICARUS {

  // ----------------------------------------------------------------------
  // Constants
  // ----------------------------------------------------------------------

  namespace BaseIds {
    enum {
      ICARUS_comms = 0x100,
      ICARUS_mcu = 0x200,
      ICARUS_flash = 0x300,
      ICARUS_adcs = 0x400,
      ICARUS_cmdDisp = 0x500,
      ICARUS_eventLogger = 0x600,
      ICARUS_timeComp = 0x700,
      ICARUS_tlmSend = 0x800,
      ICARUS_textLogger = 0x900,
      ICARUS_comDriver = 0xA00,
    };
  }

  namespace InstanceIds {
    enum {
      ICARUS_adcs,
      ICARUS_cmdDisp,
      ICARUS_comDriver,
      ICARUS_comms,
      ICARUS_eventLogger,
      ICARUS_flash,
      ICARUS_mcu,
      ICARUS_textLogger,
      ICARUS_timeComp,
      ICARUS_tlmSend,
    };
  }

  namespace Priorities {
    enum {
      ICARUS_adcs = 47,
      ICARUS_comms = 50,
      ICARUS_flash = 48,
      ICARUS_mcu = 49,
    };
  }

  namespace QueueSizes {
    enum {
      ICARUS_adcs = 10,
      ICARUS_cmdDisp = 20,
      ICARUS_comms = 10,
      ICARUS_eventLogger = 100,
      ICARUS_flash = 10,
      ICARUS_mcu = 10,
      ICARUS_tlmSend = 100,
    };
  }

  namespace StackSizes {
    enum {
      ICARUS_adcs = 65536,
      ICARUS_comms = 65536,
      ICARUS_flash = 65536,
      ICARUS_mcu = 65536,
    };
  }

  namespace TaskIds {
    enum {
      ICARUS_adcs,
      ICARUS_cmdDisp,
      ICARUS_comms,
      ICARUS_eventLogger,
      ICARUS_flash,
      ICARUS_mcu,
      ICARUS_tlmSend,
    };
  }

  // ----------------------------------------------------------------------
  // Helper functions
  // ----------------------------------------------------------------------

  //! Initialize components
  void initComponents(
      const TopologyState& state //!< The topology state
  );

  //! Configure components
  void configComponents(
      const TopologyState& state //!< The topology state
  );

  //! Set component base Ids
  void setBaseIds();

  //! Connect components
  void connectComponents();

  //! Register commands
  void regCommands();

  //! Read parameters
  void readParameters();

  //! Load parameters
  void loadParameters();

  //! Start tasks
  void startTasks(
      const TopologyState& state //!< The topology state
  );

  //! Stop tasks
  void stopTasks(
      const TopologyState& state //!< The topology state
  );

  //! Free threads
  void freeThreads(
      const TopologyState& state //!< The topology state
  );

  //! Tear down components
  void tearDownComponents(
      const TopologyState& state //!< The topology state
  );

  // ----------------------------------------------------------------------
  // Setup and teardown functions
  // ----------------------------------------------------------------------

  //! Set up the topology
  void setup(
      const TopologyState& state //!< The topology state
  );

  //! Tear down the topology
  void teardown(
      const TopologyState& state //!< The topology state
  );

}

#endif
