// ======================================================================
// \title  GpioStatusEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for GpioStatus enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Drv/GpioDriverPorts/GpioStatusEnumAc.hpp"

namespace Drv {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  GpioStatus& GpioStatus ::
    operator=(const GpioStatus& obj)
  {
    this->e = obj.e;
    return *this;
  }

  GpioStatus& GpioStatus ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const GpioStatus& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool GpioStatus ::
    isValid() const
  {
    return ((e >= OP_OK) && (e <= UNKNOWN_ERROR));
  }

  Fw::SerializeStatus GpioStatus ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus GpioStatus ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void GpioStatus ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case OP_OK:
        s = "OP_OK";
        break;
      case NOT_OPENED:
        s = "NOT_OPENED";
        break;
      case INVALID_MODE:
        s = "INVALID_MODE";
        break;
      case UNKNOWN_ERROR:
        s = "UNKNOWN_ERROR";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void GpioStatus ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
