// ======================================================================
// \title  AltitudeCmdDataSerializableAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for AltitudeCmdData struct
// ======================================================================

#include "Fw/Types/Assert.hpp"
#include "ICARUS/Types/AltitudeCmdDataSerializableAc.hpp"

namespace ICARUS {

  // ----------------------------------------------------------------------
  // Constructors
  // ----------------------------------------------------------------------

  AltitudeCmdData ::
    AltitudeCmdData() :
      Serializable(),
      m_timestamp(0),
      m_altitude(0.0f)
  {

  }

  AltitudeCmdData ::
    AltitudeCmdData(
        U32 timestamp,
        F32 altitude
    ) :
      Serializable(),
      m_timestamp(timestamp),
      m_altitude(altitude)
  {

  }

  AltitudeCmdData ::
    AltitudeCmdData(const AltitudeCmdData& obj) :
      Serializable(),
      m_timestamp(obj.m_timestamp),
      m_altitude(obj.m_altitude)
  {

  }

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  AltitudeCmdData& AltitudeCmdData ::
    operator=(const AltitudeCmdData& obj)
  {
    if (this == &obj) {
      return *this;
    }

    set(obj.m_timestamp, obj.m_altitude);
    return *this;
  }

  bool AltitudeCmdData ::
    operator==(const AltitudeCmdData& obj) const
  {
    return (
      (this->m_timestamp == obj.m_timestamp) &&
      (this->m_altitude == obj.m_altitude)
    );
  }

  bool AltitudeCmdData ::
    operator!=(const AltitudeCmdData& obj) const
  {
    return !(*this == obj);
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const AltitudeCmdData& obj) {
    Fw::String s;
    obj.toString(s);
    os << s.toChar();
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  Fw::SerializeStatus AltitudeCmdData ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    Fw::SerializeStatus status;

    status = buffer.serialize(this->m_timestamp);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }
    status = buffer.serialize(this->m_altitude);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

  Fw::SerializeStatus AltitudeCmdData ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    Fw::SerializeStatus status;

    status = buffer.deserialize(this->m_timestamp);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }
    status = buffer.deserialize(this->m_altitude);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void AltitudeCmdData ::
    toString(Fw::StringBase& sb) const
  {
    static const char* formatString =
      "( "
      "timestamp = %" PRIu32 ", "
      "altitude = %f"
      " )";

    sb.format(
      formatString,
      this->m_timestamp,
      this->m_altitude
    );
  }

#endif

  // ----------------------------------------------------------------------
  // Setter functions
  // ----------------------------------------------------------------------

  void AltitudeCmdData ::
    set(
        U32 timestamp,
        F32 altitude
    )
  {
    this->m_timestamp = timestamp;
    this->m_altitude = altitude;
  }

  void AltitudeCmdData ::
    settimestamp(U32 timestamp)
  {
    this->m_timestamp = timestamp;
  }

  void AltitudeCmdData ::
    setaltitude(F32 altitude)
  {
    this->m_altitude = altitude;
  }

}
