// ======================================================================
// \title  AltitudeCmdDataSerializableAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for AltitudeCmdData struct
// ======================================================================

#ifndef ICARUS_AltitudeCmdDataSerializableAc_HPP
#define ICARUS_AltitudeCmdDataSerializableAc_HPP

#include "FpConfig.hpp"
#include "Fw/Types/ExternalString.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/String.hpp"

namespace ICARUS {

  //! Altitude command data structure
  class AltitudeCmdData :
    public Fw::Serializable
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representation
        SERIALIZED_SIZE =
          sizeof(U32) +
          sizeof(F32)
      };

    public:

      // ----------------------------------------------------------------------
      // Constructors
      // ----------------------------------------------------------------------

      //! Constructor (default value)
      AltitudeCmdData();

      //! Member constructor
      AltitudeCmdData(
          U32 timestamp,
          F32 altitude
      );

      //! Copy constructor
      AltitudeCmdData(
          const AltitudeCmdData& obj //!< The source object
      );

    public:

      // ----------------------------------------------------------------------
      // Operators
      // ----------------------------------------------------------------------

      //! Copy assignment operator
      AltitudeCmdData& operator=(
          const AltitudeCmdData& obj //!< The source object
      );

      //! Equality operator
      bool operator==(
          const AltitudeCmdData& obj //!< The other object
      ) const;

      //! Inequality operator
      bool operator!=(
          const AltitudeCmdData& obj //!< The other object
      ) const;

#ifdef BUILD_UT

      //! Ostream operator
      friend std::ostream& operator<<(
          std::ostream& os, //!< The ostream
          const AltitudeCmdData& obj //!< The object
      );

#endif

    public:

      // ----------------------------------------------------------------------
      // Member functions
      // ----------------------------------------------------------------------

      //! Serialization
      Fw::SerializeStatus serialize(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      ) const;

      //! Deserialization
      Fw::SerializeStatus deserialize(
          Fw::SerializeBufferBase& buffer //!< The serial buffer
      );

#if FW_SERIALIZABLE_TO_STRING

      //! Convert struct to string
      void toString(
          Fw::StringBase& sb //!< The StringBase object to hold the result
      ) const;

#endif

      // ----------------------------------------------------------------------
      // Getter functions
      // ----------------------------------------------------------------------

      //! Get member timestamp
      U32 gettimestamp() const
      {
        return this->m_timestamp;
      }

      //! Get member altitude
      F32 getaltitude() const
      {
        return this->m_altitude;
      }

      // ----------------------------------------------------------------------
      // Setter functions
      // ----------------------------------------------------------------------

      //! Set all members
      void set(
          U32 timestamp,
          F32 altitude
      );

      //! Set member timestamp
      void settimestamp(U32 timestamp);

      //! Set member altitude
      void setaltitude(F32 altitude);

    protected:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      U32 m_timestamp;
      F32 m_altitude;

  };

}

#endif
