// ======================================================================
// \title  AltitudeCmdPortAc.hpp
// \author Generated by fpp-to-cpp
// \brief  hpp file for AltitudeCmd port
// ======================================================================

#ifndef ICARUS_AltitudeCmdPortAc_HPP
#define ICARUS_AltitudeCmdPortAc_HPP

#include <cstdio>
#include <cstring>

#include "FpConfig.hpp"
#include "Fw/Comp/PassiveComponentBase.hpp"
#include "Fw/Port/InputPortBase.hpp"
#include "Fw/Port/OutputPortBase.hpp"
#include "Fw/Types/Serializable.hpp"
#include "Fw/Types/StringType.hpp"
#include "ICARUS/Types/AltitudeCmdDataSerializableAc.hpp"

namespace ICARUS {

  //! Input AltitudeCmd port
  //! Altitude command port
  class InputAltitudeCmdPort :
    public Fw::InputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Constants
      // ----------------------------------------------------------------------

      enum {
        //! The size of the serial representations of the port arguments
        SERIALIZED_SIZE =
          ICARUS::AltitudeCmdData::SERIALIZED_SIZE
      };

    public:

      // ----------------------------------------------------------------------
      // Types
      // ----------------------------------------------------------------------

      //! The port callback function type
      typedef void (*CompFuncPtr)(
        Fw::PassiveComponentBase* callComp,
        FwIndexType portNum,
        const ICARUS::AltitudeCmdData& cmd
      );

    public:

      // ----------------------------------------------------------------------
      // Input Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      InputAltitudeCmdPort();

      //! Initialization function
      void init();

      //! Register a component
      void addCallComp(
          Fw::PassiveComponentBase* callComp, //!< The containing component
          CompFuncPtr funcPtr //!< The port callback function
      );

      //! Invoke a port interface
      void invoke(
          const ICARUS::AltitudeCmdData& cmd //!< The altitude command data
      );

    private:

#if FW_PORT_SERIALIZATION == 1

      //! Invoke the port with serialized arguments
      Fw::SerializeStatus invokeSerial(Fw::SerializeBufferBase& _buffer);

#endif

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the port callback function
      CompFuncPtr m_func;

  };

  //! Output AltitudeCmd port
  //! Altitude command port
  class OutputAltitudeCmdPort :
    public Fw::OutputPortBase
  {

    public:

      // ----------------------------------------------------------------------
      // Output Port Member functions
      // ----------------------------------------------------------------------

      //! Constructor
      OutputAltitudeCmdPort();

      //! Initialization function
      void init();

      //! Register an input port
      void addCallPort(
          InputAltitudeCmdPort* callPort //!< The input port
      );

      //! Invoke a port interface
      void invoke(
          const ICARUS::AltitudeCmdData& cmd //!< The altitude command data
      );

    private:

      // ----------------------------------------------------------------------
      // Member variables
      // ----------------------------------------------------------------------

      //! The pointer to the input port
      InputAltitudeCmdPort* m_port;

  };

}

#endif
