// ======================================================================
// \title  VersionTypeEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for VersionType enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Svc/Version/VersionTypeEnumAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  VersionType& VersionType ::
    operator=(const VersionType& obj)
  {
    this->e = obj.e;
    return *this;
  }

  VersionType& VersionType ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const VersionType& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool VersionType ::
    isValid() const
  {
    return ((e >= PROJECT) && (e <= ALL));
  }

  Fw::SerializeStatus VersionType ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus VersionType ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void VersionType ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case PROJECT:
        s = "PROJECT";
        break;
      case FRAMEWORK:
        s = "FRAMEWORK";
        break;
      case LIBRARY:
        s = "LIBRARY";
        break;
      case CUSTOM:
        s = "CUSTOM";
        break;
      case ALL:
        s = "ALL";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void VersionType ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
