// ======================================================================
// \title  DpHdrFieldEnumAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for DpHdrField enum
// ======================================================================

#include <cstring>
#include <limits>

#include "Fw/Types/Assert.hpp"
#include "F-Prime/Svc/DpCatalog/DpHdrFieldEnumAc.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  DpHdrField& DpHdrField ::
    operator=(const DpHdrField& obj)
  {
    this->e = obj.e;
    return *this;
  }

  DpHdrField& DpHdrField ::
    operator=(T e1)
  {
    this->e = e1;
    return *this;
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const DpHdrField& obj) {
    Fw::String s;
    obj.toString(s);
    os << s;
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  bool DpHdrField ::
    isValid() const
  {
    return ((e >= DESCRIPTOR) && (e <= CRC));
  }

  Fw::SerializeStatus DpHdrField ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    const Fw::SerializeStatus status = buffer.serialize(
        static_cast<SerialType>(this->e)
    );
    return status;
  }

  Fw::SerializeStatus DpHdrField ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    SerialType es;
    Fw::SerializeStatus status = buffer.deserialize(es);
    if (status == Fw::FW_SERIALIZE_OK) {
      this->e = static_cast<T>(es);
      if (!this->isValid()) {
        status = Fw::FW_DESERIALIZE_FORMAT_ERROR;
      }
    }
    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void DpHdrField ::
    toString(Fw::StringBase& sb) const
  {
    Fw::String s;
    switch (e) {
      case DESCRIPTOR:
        s = "DESCRIPTOR";
        break;
      case ID:
        s = "ID";
        break;
      case PRIORITY:
        s = "PRIORITY";
        break;
      case CRC:
        s = "CRC";
        break;
      default:
        s = "[invalid]";
        break;
    }
    sb.format("%s (%" PRIi32 ")", s.toChar(), e);
  }

#elif FW_ENABLE_TEXT_LOGGING

  void DpHdrField ::
    toString(Fw::StringBase& sb) const
  {
    sb.format("%" PRIi32 "", e);
  }

#endif

}
