// ======================================================================
// \title  SendFileResponseSerializableAc.cpp
// \author Generated by fpp-to-cpp
// \brief  cpp file for SendFileResponse struct
// ======================================================================

#include "F-Prime/Svc/FileDownlinkPorts/SendFileResponseSerializableAc.hpp"
#include "Fw/Types/Assert.hpp"

namespace Svc {

  // ----------------------------------------------------------------------
  // Constructors
  // ----------------------------------------------------------------------

  SendFileResponse ::
    SendFileResponse() :
      Serializable(),
      m_status(Svc::SendFileStatus::STATUS_OK),
      m_context(0)
  {

  }

  SendFileResponse ::
    SendFileResponse(
        Svc::SendFileStatus::T status,
        U32 context
    ) :
      Serializable(),
      m_status(status),
      m_context(context)
  {

  }

  SendFileResponse ::
    SendFileResponse(const SendFileResponse& obj) :
      Serializable(),
      m_status(obj.m_status),
      m_context(obj.m_context)
  {

  }

  // ----------------------------------------------------------------------
  // Operators
  // ----------------------------------------------------------------------

  SendFileResponse& SendFileResponse ::
    operator=(const SendFileResponse& obj)
  {
    if (this == &obj) {
      return *this;
    }

    set(obj.m_status, obj.m_context);
    return *this;
  }

  bool SendFileResponse ::
    operator==(const SendFileResponse& obj) const
  {
    return (
      (this->m_status == obj.m_status) &&
      (this->m_context == obj.m_context)
    );
  }

  bool SendFileResponse ::
    operator!=(const SendFileResponse& obj) const
  {
    return !(*this == obj);
  }

#ifdef BUILD_UT

  std::ostream& operator<<(std::ostream& os, const SendFileResponse& obj) {
    Fw::String s;
    obj.toString(s);
    os << s.toChar();
    return os;
  }

#endif

  // ----------------------------------------------------------------------
  // Member functions
  // ----------------------------------------------------------------------

  Fw::SerializeStatus SendFileResponse ::
    serialize(Fw::SerializeBufferBase& buffer) const
  {
    Fw::SerializeStatus status;

    status = buffer.serialize(this->m_status);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }
    status = buffer.serialize(this->m_context);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

  Fw::SerializeStatus SendFileResponse ::
    deserialize(Fw::SerializeBufferBase& buffer)
  {
    Fw::SerializeStatus status;

    status = buffer.deserialize(this->m_status);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }
    status = buffer.deserialize(this->m_context);
    if (status != Fw::FW_SERIALIZE_OK) {
      return status;
    }

    return status;
  }

#if FW_SERIALIZABLE_TO_STRING

  void SendFileResponse ::
    toString(Fw::StringBase& sb) const
  {
    static const char* formatString =
      "( "
      "status = %s, "
      "context = %" PRIu32 ""
      " )";

    // Declare strings to hold any serializable toString() arguments
    Fw::String statusStr;

    // Call toString for arrays and serializable types
    this->m_status.toString(statusStr);

    sb.format(
      formatString,
      statusStr.toChar(),
      this->m_context
    );
  }

#endif

  // ----------------------------------------------------------------------
  // Setter functions
  // ----------------------------------------------------------------------

  void SendFileResponse ::
    set(
        Svc::SendFileStatus::T status,
        U32 context
    )
  {
    this->m_status = status;
    this->m_context = context;
  }

  void SendFileResponse ::
    setstatus(Svc::SendFileStatus::T status)
  {
    this->m_status = status;
  }

  void SendFileResponse ::
    setcontext(U32 context)
  {
    this->m_context = context;
  }

}
