/*
    This file has been autogenerated using [generate_version_info.py].
    This file may be overwritten.
*/
#include "version.hpp"

namespace Project {

    const char* const Version::FRAMEWORK_VERSION = "v3.5.0";
    const char* const Version::PROJECT_VERSION = "v3.5.0";
    const FwIndexType Version::LIBRARY_VERSIONS_COUNT = 1; 
    const char* const Version::LIBRARY_VERSIONS[] = { 
        "lib@v3.5.0",
    };
}  // namespace Project
